# Generated by Django 2.2.16 on 2020-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Demo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name_plural": "Demo",
            },
        ),
    ]
